sudo: false
cache: bundler
language: ruby
bundler_args: --without development
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - 2.3.1
env:
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
notifications:
  email: false
